# -*- coding: utf-8 -*-
"""AdsCTROptimisation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P1RWYgoJ7MbeClIGRS4BcpD585Q_3Plq
"""

import pandas as pd
import math
import matplotlib.pyplot as plt
dataset = pd.read_csv("/content/Ads_CTR_Optimisation.csv")
N = len(dataset)
d = len(dataset.columns)
ads_selected = []
numbers_of_selections = [0] * d
sums_of_rewards = [0] * d
total_reward = 0
for n in range(N):
    ad = 0
    max_upper_bound = 0
    for i in range(d):
        if numbers_of_selections[i] > 0:
            average_reward = sums_of_rewards[i] / numbers_of_selections[i]
            delta_i = math.sqrt((3 / 2) * math.log(n + 1) / numbers_of_selections[i])
            upper_bound = average_reward + delta_i
        else:
            upper_bound = float('inf')

        if upper_bound > max_upper_bound:
            max_upper_bound = upper_bound
            ad = i
    ads_selected.append(ad)
    numbers_of_selections[ad] += 1
    reward = dataset.values[n, ad]
    sums_of_rewards[ad] += reward
    total_reward += reward
plt.hist(ads_selected)
plt.title("Histogram of Ad Selections")
plt.xlabel("Advertisements")
plt.ylabel("Number of Times Selected")
plt.show()